/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/Dashboard/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/Dashboard/Users/index'
import { Route as DashboardSeriesIndexRouteImport } from './routes/Dashboard/Series/index'
import { Route as DashboardRaceIndexRouteImport } from './routes/Dashboard/Race/index'
import { Route as DashboardHardwareIndexRouteImport } from './routes/Dashboard/Hardware/index'
import { Route as DashboardDocumentationIndexRouteImport } from './routes/Dashboard/Documentation/index'
import { Route as DashboardClubIndexRouteImport } from './routes/Dashboard/Club/index'
import { Route as DashboardBoatsIndexRouteImport } from './routes/Dashboard/Boats/index'
import { Route as DashboardSeriesSeriesIdRouteImport } from './routes/Dashboard/Series/$seriesId'
import { Route as DashboardRaceRaceIdRouteImport } from './routes/Dashboard/Race/$raceId'
import { Route as DashboardPrintPaperResultsRaceIdRouteImport } from './routes/Dashboard/PrintPaperResults/$raceId'

const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/Dashboard/',
  path: '/Dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/Dashboard/Users/',
  path: '/Dashboard/Users/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSeriesIndexRoute = DashboardSeriesIndexRouteImport.update({
  id: '/Dashboard/Series/',
  path: '/Dashboard/Series/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRaceIndexRoute = DashboardRaceIndexRouteImport.update({
  id: '/Dashboard/Race/',
  path: '/Dashboard/Race/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHardwareIndexRoute = DashboardHardwareIndexRouteImport.update({
  id: '/Dashboard/Hardware/',
  path: '/Dashboard/Hardware/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDocumentationIndexRoute =
  DashboardDocumentationIndexRouteImport.update({
    id: '/Dashboard/Documentation/',
    path: '/Dashboard/Documentation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClubIndexRoute = DashboardClubIndexRouteImport.update({
  id: '/Dashboard/Club/',
  path: '/Dashboard/Club/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBoatsIndexRoute = DashboardBoatsIndexRouteImport.update({
  id: '/Dashboard/Boats/',
  path: '/Dashboard/Boats/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSeriesSeriesIdRoute = DashboardSeriesSeriesIdRouteImport.update({
  id: '/Dashboard/Series/$seriesId',
  path: '/Dashboard/Series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRaceRaceIdRoute = DashboardRaceRaceIdRouteImport.update({
  id: '/Dashboard/Race/$raceId',
  path: '/Dashboard/Race/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPrintPaperResultsRaceIdRoute =
  DashboardPrintPaperResultsRaceIdRouteImport.update({
    id: '/Dashboard/PrintPaperResults/$raceId',
    path: '/Dashboard/PrintPaperResults/$raceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Dashboard': typeof DashboardIndexRoute
  '/Dashboard/PrintPaperResults/$raceId': typeof DashboardPrintPaperResultsRaceIdRoute
  '/Dashboard/Race/$raceId': typeof DashboardRaceRaceIdRoute
  '/Dashboard/Series/$seriesId': typeof DashboardSeriesSeriesIdRoute
  '/Dashboard/Boats': typeof DashboardBoatsIndexRoute
  '/Dashboard/Club': typeof DashboardClubIndexRoute
  '/Dashboard/Documentation': typeof DashboardDocumentationIndexRoute
  '/Dashboard/Hardware': typeof DashboardHardwareIndexRoute
  '/Dashboard/Race': typeof DashboardRaceIndexRoute
  '/Dashboard/Series': typeof DashboardSeriesIndexRoute
  '/Dashboard/Users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Dashboard': typeof DashboardIndexRoute
  '/Dashboard/PrintPaperResults/$raceId': typeof DashboardPrintPaperResultsRaceIdRoute
  '/Dashboard/Race/$raceId': typeof DashboardRaceRaceIdRoute
  '/Dashboard/Series/$seriesId': typeof DashboardSeriesSeriesIdRoute
  '/Dashboard/Boats': typeof DashboardBoatsIndexRoute
  '/Dashboard/Club': typeof DashboardClubIndexRoute
  '/Dashboard/Documentation': typeof DashboardDocumentationIndexRoute
  '/Dashboard/Hardware': typeof DashboardHardwareIndexRoute
  '/Dashboard/Race': typeof DashboardRaceIndexRoute
  '/Dashboard/Series': typeof DashboardSeriesIndexRoute
  '/Dashboard/Users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Dashboard/': typeof DashboardIndexRoute
  '/Dashboard/PrintPaperResults/$raceId': typeof DashboardPrintPaperResultsRaceIdRoute
  '/Dashboard/Race/$raceId': typeof DashboardRaceRaceIdRoute
  '/Dashboard/Series/$seriesId': typeof DashboardSeriesSeriesIdRoute
  '/Dashboard/Boats/': typeof DashboardBoatsIndexRoute
  '/Dashboard/Club/': typeof DashboardClubIndexRoute
  '/Dashboard/Documentation/': typeof DashboardDocumentationIndexRoute
  '/Dashboard/Hardware/': typeof DashboardHardwareIndexRoute
  '/Dashboard/Race/': typeof DashboardRaceIndexRoute
  '/Dashboard/Series/': typeof DashboardSeriesIndexRoute
  '/Dashboard/Users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Login'
    | '/Dashboard'
    | '/Dashboard/PrintPaperResults/$raceId'
    | '/Dashboard/Race/$raceId'
    | '/Dashboard/Series/$seriesId'
    | '/Dashboard/Boats'
    | '/Dashboard/Club'
    | '/Dashboard/Documentation'
    | '/Dashboard/Hardware'
    | '/Dashboard/Race'
    | '/Dashboard/Series'
    | '/Dashboard/Users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Login'
    | '/Dashboard'
    | '/Dashboard/PrintPaperResults/$raceId'
    | '/Dashboard/Race/$raceId'
    | '/Dashboard/Series/$seriesId'
    | '/Dashboard/Boats'
    | '/Dashboard/Club'
    | '/Dashboard/Documentation'
    | '/Dashboard/Hardware'
    | '/Dashboard/Race'
    | '/Dashboard/Series'
    | '/Dashboard/Users'
  id:
    | '__root__'
    | '/'
    | '/Login'
    | '/Dashboard/'
    | '/Dashboard/PrintPaperResults/$raceId'
    | '/Dashboard/Race/$raceId'
    | '/Dashboard/Series/$seriesId'
    | '/Dashboard/Boats/'
    | '/Dashboard/Club/'
    | '/Dashboard/Documentation/'
    | '/Dashboard/Hardware/'
    | '/Dashboard/Race/'
    | '/Dashboard/Series/'
    | '/Dashboard/Users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPrintPaperResultsRaceIdRoute: typeof DashboardPrintPaperResultsRaceIdRoute
  DashboardRaceRaceIdRoute: typeof DashboardRaceRaceIdRoute
  DashboardSeriesSeriesIdRoute: typeof DashboardSeriesSeriesIdRoute
  DashboardBoatsIndexRoute: typeof DashboardBoatsIndexRoute
  DashboardClubIndexRoute: typeof DashboardClubIndexRoute
  DashboardDocumentationIndexRoute: typeof DashboardDocumentationIndexRoute
  DashboardHardwareIndexRoute: typeof DashboardHardwareIndexRoute
  DashboardRaceIndexRoute: typeof DashboardRaceIndexRoute
  DashboardSeriesIndexRoute: typeof DashboardSeriesIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/': {
      id: '/Dashboard/'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/Users/': {
      id: '/Dashboard/Users/'
      path: '/Dashboard/Users'
      fullPath: '/Dashboard/Users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/Series/': {
      id: '/Dashboard/Series/'
      path: '/Dashboard/Series'
      fullPath: '/Dashboard/Series'
      preLoaderRoute: typeof DashboardSeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/Race/': {
      id: '/Dashboard/Race/'
      path: '/Dashboard/Race'
      fullPath: '/Dashboard/Race'
      preLoaderRoute: typeof DashboardRaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/Hardware/': {
      id: '/Dashboard/Hardware/'
      path: '/Dashboard/Hardware'
      fullPath: '/Dashboard/Hardware'
      preLoaderRoute: typeof DashboardHardwareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/Documentation/': {
      id: '/Dashboard/Documentation/'
      path: '/Dashboard/Documentation'
      fullPath: '/Dashboard/Documentation'
      preLoaderRoute: typeof DashboardDocumentationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/Club/': {
      id: '/Dashboard/Club/'
      path: '/Dashboard/Club'
      fullPath: '/Dashboard/Club'
      preLoaderRoute: typeof DashboardClubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/Boats/': {
      id: '/Dashboard/Boats/'
      path: '/Dashboard/Boats'
      fullPath: '/Dashboard/Boats'
      preLoaderRoute: typeof DashboardBoatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/Series/$seriesId': {
      id: '/Dashboard/Series/$seriesId'
      path: '/Dashboard/Series/$seriesId'
      fullPath: '/Dashboard/Series/$seriesId'
      preLoaderRoute: typeof DashboardSeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/Race/$raceId': {
      id: '/Dashboard/Race/$raceId'
      path: '/Dashboard/Race/$raceId'
      fullPath: '/Dashboard/Race/$raceId'
      preLoaderRoute: typeof DashboardRaceRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/PrintPaperResults/$raceId': {
      id: '/Dashboard/PrintPaperResults/$raceId'
      path: '/Dashboard/PrintPaperResults/$raceId'
      fullPath: '/Dashboard/PrintPaperResults/$raceId'
      preLoaderRoute: typeof DashboardPrintPaperResultsRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPrintPaperResultsRaceIdRoute: DashboardPrintPaperResultsRaceIdRoute,
  DashboardRaceRaceIdRoute: DashboardRaceRaceIdRoute,
  DashboardSeriesSeriesIdRoute: DashboardSeriesSeriesIdRoute,
  DashboardBoatsIndexRoute: DashboardBoatsIndexRoute,
  DashboardClubIndexRoute: DashboardClubIndexRoute,
  DashboardDocumentationIndexRoute: DashboardDocumentationIndexRoute,
  DashboardHardwareIndexRoute: DashboardHardwareIndexRoute,
  DashboardRaceIndexRoute: DashboardRaceIndexRoute,
  DashboardSeriesIndexRoute: DashboardSeriesIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
