/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ClubIndexRouteImport } from './routes/club/index'
import { Route as AuthsorterIndexRouteImport } from './routes/authsorter/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SignOnIndexRouteImport } from './routes/SignOn/index'
import { Route as RegisterIndexRouteImport } from './routes/Register/index'
import { Route as LogoutIndexRouteImport } from './routes/Logout/index'
import { Route as DemoIndexRouteImport } from './routes/Demo/index'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as AutoLoginUUIDRouteImport } from './routes/autoLogin/$UUID'
import { Route as PricingPageRouteImport } from './routes/Pricing/page'
import { Route as PRaceRaceIdRouteImport } from './routes/PRace/$raceId'
import { Route as HRaceRaceIdRouteImport } from './routes/HRace/$raceId'
import { Route as CastControlClubIdRouteImport } from './routes/CastControl/$clubId'
import { Route as CastClubIdRouteImport } from './routes/Cast/$clubId'
import { Route as DashboardMeIndexRouteImport } from './routes/dashboard/me/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/Users/index'
import { Route as DashboardTrackableIndexRouteImport } from './routes/dashboard/Trackable/index'
import { Route as DashboardSubscriptionIndexRouteImport } from './routes/dashboard/Subscription/index'
import { Route as DashboardSeriesIndexRouteImport } from './routes/dashboard/Series/index'
import { Route as DashboardRaceIndexRouteImport } from './routes/dashboard/Race/index'
import { Route as DashboardHardwareIndexRouteImport } from './routes/dashboard/Hardware/index'
import { Route as DashboardDocumentationIndexRouteImport } from './routes/dashboard/Documentation/index'
import { Route as DashboardClubIndexRouteImport } from './routes/dashboard/Club/index'
import { Route as DashboardBoatsIndexRouteImport } from './routes/dashboard/Boats/index'
import { Route as ClubClubNameIndexRouteImport } from './routes/club/$clubName/index'
import { Route as AdminClubsIndexRouteImport } from './routes/admin/clubs/index'
import { Route as SignOnGuideIndexRouteImport } from './routes/SignOn/Guide/index'
import { Route as DashboardMeRacesRouteImport } from './routes/dashboard/me/races'
import { Route as DashboardMeClubsRouteImport } from './routes/dashboard/me/clubs'
import { Route as DashboardSeriesSeriesIdRouteImport } from './routes/dashboard/Series/$seriesId'
import { Route as DashboardRaceRaceIdRouteImport } from './routes/dashboard/Race/$raceId'
import { Route as DashboardPrintPaperResultsRaceIdRouteImport } from './routes/dashboard/PrintPaperResults/$raceId'
import { Route as AdminSettingsDemoRouteImport } from './routes/admin/settings/demo'
import { Route as AdminClubsClubIdRouteImport } from './routes/admin/clubs/$clubId'
import { Route as SignOnSeriesSeriesIdRouteImport } from './routes/SignOn/Series/$seriesId'
import { Route as SignOnRaceRaceIdRouteImport } from './routes/SignOn/Race/$raceId'
import { Route as DemoRaceRaceIdRouteImport } from './routes/Demo/Race/$raceId'
import { Route as ClubClubNameLiveResultsIndexRouteImport } from './routes/club/$clubName/LiveResults/index'
import { Route as ClubClubNameSeriesSeriesIdRouteImport } from './routes/club/$clubName/Series/$seriesId'
import { Route as ClubClubNameRaceRaceIdRouteImport } from './routes/club/$clubName/Race/$raceId'

const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/club/',
  path: '/club/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthsorterIndexRoute = AuthsorterIndexRouteImport.update({
  id: '/authsorter/',
  path: '/authsorter/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOnIndexRoute = SignOnIndexRouteImport.update({
  id: '/SignOn/',
  path: '/SignOn/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/Register/',
  path: '/Register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutIndexRoute = LogoutIndexRouteImport.update({
  id: '/Logout/',
  path: '/Logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/Demo/',
  path: '/Demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/dashboard/home',
  path: '/dashboard/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoLoginUUIDRoute = AutoLoginUUIDRouteImport.update({
  id: '/autoLogin/$UUID',
  path: '/autoLogin/$UUID',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingPageRoute = PricingPageRouteImport.update({
  id: '/Pricing/page',
  path: '/Pricing/page',
  getParentRoute: () => rootRouteImport,
} as any)
const PRaceRaceIdRoute = PRaceRaceIdRouteImport.update({
  id: '/PRace/$raceId',
  path: '/PRace/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const HRaceRaceIdRoute = HRaceRaceIdRouteImport.update({
  id: '/HRace/$raceId',
  path: '/HRace/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CastControlClubIdRoute = CastControlClubIdRouteImport.update({
  id: '/CastControl/$clubId',
  path: '/CastControl/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const CastClubIdRoute = CastClubIdRouteImport.update({
  id: '/Cast/$clubId',
  path: '/Cast/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMeIndexRoute = DashboardMeIndexRouteImport.update({
  id: '/dashboard/me/',
  path: '/dashboard/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/dashboard/Users/',
  path: '/dashboard/Users/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrackableIndexRoute = DashboardTrackableIndexRouteImport.update({
  id: '/dashboard/Trackable/',
  path: '/dashboard/Trackable/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubscriptionIndexRoute =
  DashboardSubscriptionIndexRouteImport.update({
    id: '/dashboard/Subscription/',
    path: '/dashboard/Subscription/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSeriesIndexRoute = DashboardSeriesIndexRouteImport.update({
  id: '/dashboard/Series/',
  path: '/dashboard/Series/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRaceIndexRoute = DashboardRaceIndexRouteImport.update({
  id: '/dashboard/Race/',
  path: '/dashboard/Race/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHardwareIndexRoute = DashboardHardwareIndexRouteImport.update({
  id: '/dashboard/Hardware/',
  path: '/dashboard/Hardware/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDocumentationIndexRoute =
  DashboardDocumentationIndexRouteImport.update({
    id: '/dashboard/Documentation/',
    path: '/dashboard/Documentation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClubIndexRoute = DashboardClubIndexRouteImport.update({
  id: '/dashboard/Club/',
  path: '/dashboard/Club/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBoatsIndexRoute = DashboardBoatsIndexRouteImport.update({
  id: '/dashboard/Boats/',
  path: '/dashboard/Boats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubClubNameIndexRoute = ClubClubNameIndexRouteImport.update({
  id: '/club/$clubName/',
  path: '/club/$clubName/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClubsIndexRoute = AdminClubsIndexRouteImport.update({
  id: '/admin/clubs/',
  path: '/admin/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOnGuideIndexRoute = SignOnGuideIndexRouteImport.update({
  id: '/SignOn/Guide/',
  path: '/SignOn/Guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMeRacesRoute = DashboardMeRacesRouteImport.update({
  id: '/dashboard/me/races',
  path: '/dashboard/me/races',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMeClubsRoute = DashboardMeClubsRouteImport.update({
  id: '/dashboard/me/clubs',
  path: '/dashboard/me/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSeriesSeriesIdRoute = DashboardSeriesSeriesIdRouteImport.update({
  id: '/dashboard/Series/$seriesId',
  path: '/dashboard/Series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRaceRaceIdRoute = DashboardRaceRaceIdRouteImport.update({
  id: '/dashboard/Race/$raceId',
  path: '/dashboard/Race/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPrintPaperResultsRaceIdRoute =
  DashboardPrintPaperResultsRaceIdRouteImport.update({
    id: '/dashboard/PrintPaperResults/$raceId',
    path: '/dashboard/PrintPaperResults/$raceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSettingsDemoRoute = AdminSettingsDemoRouteImport.update({
  id: '/admin/settings/demo',
  path: '/admin/settings/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClubsClubIdRoute = AdminClubsClubIdRouteImport.update({
  id: '/admin/clubs/$clubId',
  path: '/admin/clubs/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOnSeriesSeriesIdRoute = SignOnSeriesSeriesIdRouteImport.update({
  id: '/SignOn/Series/$seriesId',
  path: '/SignOn/Series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOnRaceRaceIdRoute = SignOnRaceRaceIdRouteImport.update({
  id: '/SignOn/Race/$raceId',
  path: '/SignOn/Race/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRaceRaceIdRoute = DemoRaceRaceIdRouteImport.update({
  id: '/Demo/Race/$raceId',
  path: '/Demo/Race/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubClubNameLiveResultsIndexRoute =
  ClubClubNameLiveResultsIndexRouteImport.update({
    id: '/club/$clubName/LiveResults/',
    path: '/club/$clubName/LiveResults/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClubClubNameSeriesSeriesIdRoute =
  ClubClubNameSeriesSeriesIdRouteImport.update({
    id: '/club/$clubName/Series/$seriesId',
    path: '/club/$clubName/Series/$seriesId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClubClubNameRaceRaceIdRoute = ClubClubNameRaceRaceIdRouteImport.update({
  id: '/club/$clubName/Race/$raceId',
  path: '/club/$clubName/Race/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Cast/$clubId': typeof CastClubIdRoute
  '/CastControl/$clubId': typeof CastControlClubIdRoute
  '/HRace/$raceId': typeof HRaceRaceIdRoute
  '/PRace/$raceId': typeof PRaceRaceIdRoute
  '/Pricing/page': typeof PricingPageRoute
  '/autoLogin/$UUID': typeof AutoLoginUUIDRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/Demo': typeof DemoIndexRoute
  '/Logout': typeof LogoutIndexRoute
  '/Register': typeof RegisterIndexRoute
  '/SignOn': typeof SignOnIndexRoute
  '/admin': typeof AdminIndexRoute
  '/authsorter': typeof AuthsorterIndexRoute
  '/club': typeof ClubIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/Demo/Race/$raceId': typeof DemoRaceRaceIdRoute
  '/SignOn/Race/$raceId': typeof SignOnRaceRaceIdRoute
  '/SignOn/Series/$seriesId': typeof SignOnSeriesSeriesIdRoute
  '/admin/clubs/$clubId': typeof AdminClubsClubIdRoute
  '/admin/settings/demo': typeof AdminSettingsDemoRoute
  '/dashboard/PrintPaperResults/$raceId': typeof DashboardPrintPaperResultsRaceIdRoute
  '/dashboard/Race/$raceId': typeof DashboardRaceRaceIdRoute
  '/dashboard/Series/$seriesId': typeof DashboardSeriesSeriesIdRoute
  '/dashboard/me/clubs': typeof DashboardMeClubsRoute
  '/dashboard/me/races': typeof DashboardMeRacesRoute
  '/SignOn/Guide': typeof SignOnGuideIndexRoute
  '/admin/clubs': typeof AdminClubsIndexRoute
  '/club/$clubName': typeof ClubClubNameIndexRoute
  '/dashboard/Boats': typeof DashboardBoatsIndexRoute
  '/dashboard/Club': typeof DashboardClubIndexRoute
  '/dashboard/Documentation': typeof DashboardDocumentationIndexRoute
  '/dashboard/Hardware': typeof DashboardHardwareIndexRoute
  '/dashboard/Race': typeof DashboardRaceIndexRoute
  '/dashboard/Series': typeof DashboardSeriesIndexRoute
  '/dashboard/Subscription': typeof DashboardSubscriptionIndexRoute
  '/dashboard/Trackable': typeof DashboardTrackableIndexRoute
  '/dashboard/Users': typeof DashboardUsersIndexRoute
  '/dashboard/me': typeof DashboardMeIndexRoute
  '/club/$clubName/Race/$raceId': typeof ClubClubNameRaceRaceIdRoute
  '/club/$clubName/Series/$seriesId': typeof ClubClubNameSeriesSeriesIdRoute
  '/club/$clubName/LiveResults': typeof ClubClubNameLiveResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Cast/$clubId': typeof CastClubIdRoute
  '/CastControl/$clubId': typeof CastControlClubIdRoute
  '/HRace/$raceId': typeof HRaceRaceIdRoute
  '/PRace/$raceId': typeof PRaceRaceIdRoute
  '/Pricing/page': typeof PricingPageRoute
  '/autoLogin/$UUID': typeof AutoLoginUUIDRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/Demo': typeof DemoIndexRoute
  '/Logout': typeof LogoutIndexRoute
  '/Register': typeof RegisterIndexRoute
  '/SignOn': typeof SignOnIndexRoute
  '/admin': typeof AdminIndexRoute
  '/authsorter': typeof AuthsorterIndexRoute
  '/club': typeof ClubIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/Demo/Race/$raceId': typeof DemoRaceRaceIdRoute
  '/SignOn/Race/$raceId': typeof SignOnRaceRaceIdRoute
  '/SignOn/Series/$seriesId': typeof SignOnSeriesSeriesIdRoute
  '/admin/clubs/$clubId': typeof AdminClubsClubIdRoute
  '/admin/settings/demo': typeof AdminSettingsDemoRoute
  '/dashboard/PrintPaperResults/$raceId': typeof DashboardPrintPaperResultsRaceIdRoute
  '/dashboard/Race/$raceId': typeof DashboardRaceRaceIdRoute
  '/dashboard/Series/$seriesId': typeof DashboardSeriesSeriesIdRoute
  '/dashboard/me/clubs': typeof DashboardMeClubsRoute
  '/dashboard/me/races': typeof DashboardMeRacesRoute
  '/SignOn/Guide': typeof SignOnGuideIndexRoute
  '/admin/clubs': typeof AdminClubsIndexRoute
  '/club/$clubName': typeof ClubClubNameIndexRoute
  '/dashboard/Boats': typeof DashboardBoatsIndexRoute
  '/dashboard/Club': typeof DashboardClubIndexRoute
  '/dashboard/Documentation': typeof DashboardDocumentationIndexRoute
  '/dashboard/Hardware': typeof DashboardHardwareIndexRoute
  '/dashboard/Race': typeof DashboardRaceIndexRoute
  '/dashboard/Series': typeof DashboardSeriesIndexRoute
  '/dashboard/Subscription': typeof DashboardSubscriptionIndexRoute
  '/dashboard/Trackable': typeof DashboardTrackableIndexRoute
  '/dashboard/Users': typeof DashboardUsersIndexRoute
  '/dashboard/me': typeof DashboardMeIndexRoute
  '/club/$clubName/Race/$raceId': typeof ClubClubNameRaceRaceIdRoute
  '/club/$clubName/Series/$seriesId': typeof ClubClubNameSeriesSeriesIdRoute
  '/club/$clubName/LiveResults': typeof ClubClubNameLiveResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Cast/$clubId': typeof CastClubIdRoute
  '/CastControl/$clubId': typeof CastControlClubIdRoute
  '/HRace/$raceId': typeof HRaceRaceIdRoute
  '/PRace/$raceId': typeof PRaceRaceIdRoute
  '/Pricing/page': typeof PricingPageRoute
  '/autoLogin/$UUID': typeof AutoLoginUUIDRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/Demo/': typeof DemoIndexRoute
  '/Logout/': typeof LogoutIndexRoute
  '/Register/': typeof RegisterIndexRoute
  '/SignOn/': typeof SignOnIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/authsorter/': typeof AuthsorterIndexRoute
  '/club/': typeof ClubIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/Demo/Race/$raceId': typeof DemoRaceRaceIdRoute
  '/SignOn/Race/$raceId': typeof SignOnRaceRaceIdRoute
  '/SignOn/Series/$seriesId': typeof SignOnSeriesSeriesIdRoute
  '/admin/clubs/$clubId': typeof AdminClubsClubIdRoute
  '/admin/settings/demo': typeof AdminSettingsDemoRoute
  '/dashboard/PrintPaperResults/$raceId': typeof DashboardPrintPaperResultsRaceIdRoute
  '/dashboard/Race/$raceId': typeof DashboardRaceRaceIdRoute
  '/dashboard/Series/$seriesId': typeof DashboardSeriesSeriesIdRoute
  '/dashboard/me/clubs': typeof DashboardMeClubsRoute
  '/dashboard/me/races': typeof DashboardMeRacesRoute
  '/SignOn/Guide/': typeof SignOnGuideIndexRoute
  '/admin/clubs/': typeof AdminClubsIndexRoute
  '/club/$clubName/': typeof ClubClubNameIndexRoute
  '/dashboard/Boats/': typeof DashboardBoatsIndexRoute
  '/dashboard/Club/': typeof DashboardClubIndexRoute
  '/dashboard/Documentation/': typeof DashboardDocumentationIndexRoute
  '/dashboard/Hardware/': typeof DashboardHardwareIndexRoute
  '/dashboard/Race/': typeof DashboardRaceIndexRoute
  '/dashboard/Series/': typeof DashboardSeriesIndexRoute
  '/dashboard/Subscription/': typeof DashboardSubscriptionIndexRoute
  '/dashboard/Trackable/': typeof DashboardTrackableIndexRoute
  '/dashboard/Users/': typeof DashboardUsersIndexRoute
  '/dashboard/me/': typeof DashboardMeIndexRoute
  '/club/$clubName/Race/$raceId': typeof ClubClubNameRaceRaceIdRoute
  '/club/$clubName/Series/$seriesId': typeof ClubClubNameSeriesSeriesIdRoute
  '/club/$clubName/LiveResults/': typeof ClubClubNameLiveResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Login'
    | '/Cast/$clubId'
    | '/CastControl/$clubId'
    | '/HRace/$raceId'
    | '/PRace/$raceId'
    | '/Pricing/page'
    | '/autoLogin/$UUID'
    | '/dashboard/home'
    | '/Demo'
    | '/Logout'
    | '/Register'
    | '/SignOn'
    | '/admin'
    | '/authsorter'
    | '/club'
    | '/dashboard'
    | '/Demo/Race/$raceId'
    | '/SignOn/Race/$raceId'
    | '/SignOn/Series/$seriesId'
    | '/admin/clubs/$clubId'
    | '/admin/settings/demo'
    | '/dashboard/PrintPaperResults/$raceId'
    | '/dashboard/Race/$raceId'
    | '/dashboard/Series/$seriesId'
    | '/dashboard/me/clubs'
    | '/dashboard/me/races'
    | '/SignOn/Guide'
    | '/admin/clubs'
    | '/club/$clubName'
    | '/dashboard/Boats'
    | '/dashboard/Club'
    | '/dashboard/Documentation'
    | '/dashboard/Hardware'
    | '/dashboard/Race'
    | '/dashboard/Series'
    | '/dashboard/Subscription'
    | '/dashboard/Trackable'
    | '/dashboard/Users'
    | '/dashboard/me'
    | '/club/$clubName/Race/$raceId'
    | '/club/$clubName/Series/$seriesId'
    | '/club/$clubName/LiveResults'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Login'
    | '/Cast/$clubId'
    | '/CastControl/$clubId'
    | '/HRace/$raceId'
    | '/PRace/$raceId'
    | '/Pricing/page'
    | '/autoLogin/$UUID'
    | '/dashboard/home'
    | '/Demo'
    | '/Logout'
    | '/Register'
    | '/SignOn'
    | '/admin'
    | '/authsorter'
    | '/club'
    | '/dashboard'
    | '/Demo/Race/$raceId'
    | '/SignOn/Race/$raceId'
    | '/SignOn/Series/$seriesId'
    | '/admin/clubs/$clubId'
    | '/admin/settings/demo'
    | '/dashboard/PrintPaperResults/$raceId'
    | '/dashboard/Race/$raceId'
    | '/dashboard/Series/$seriesId'
    | '/dashboard/me/clubs'
    | '/dashboard/me/races'
    | '/SignOn/Guide'
    | '/admin/clubs'
    | '/club/$clubName'
    | '/dashboard/Boats'
    | '/dashboard/Club'
    | '/dashboard/Documentation'
    | '/dashboard/Hardware'
    | '/dashboard/Race'
    | '/dashboard/Series'
    | '/dashboard/Subscription'
    | '/dashboard/Trackable'
    | '/dashboard/Users'
    | '/dashboard/me'
    | '/club/$clubName/Race/$raceId'
    | '/club/$clubName/Series/$seriesId'
    | '/club/$clubName/LiveResults'
  id:
    | '__root__'
    | '/'
    | '/Login'
    | '/Cast/$clubId'
    | '/CastControl/$clubId'
    | '/HRace/$raceId'
    | '/PRace/$raceId'
    | '/Pricing/page'
    | '/autoLogin/$UUID'
    | '/dashboard/home'
    | '/Demo/'
    | '/Logout/'
    | '/Register/'
    | '/SignOn/'
    | '/admin/'
    | '/authsorter/'
    | '/club/'
    | '/dashboard/'
    | '/Demo/Race/$raceId'
    | '/SignOn/Race/$raceId'
    | '/SignOn/Series/$seriesId'
    | '/admin/clubs/$clubId'
    | '/admin/settings/demo'
    | '/dashboard/PrintPaperResults/$raceId'
    | '/dashboard/Race/$raceId'
    | '/dashboard/Series/$seriesId'
    | '/dashboard/me/clubs'
    | '/dashboard/me/races'
    | '/SignOn/Guide/'
    | '/admin/clubs/'
    | '/club/$clubName/'
    | '/dashboard/Boats/'
    | '/dashboard/Club/'
    | '/dashboard/Documentation/'
    | '/dashboard/Hardware/'
    | '/dashboard/Race/'
    | '/dashboard/Series/'
    | '/dashboard/Subscription/'
    | '/dashboard/Trackable/'
    | '/dashboard/Users/'
    | '/dashboard/me/'
    | '/club/$clubName/Race/$raceId'
    | '/club/$clubName/Series/$seriesId'
    | '/club/$clubName/LiveResults/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CastClubIdRoute: typeof CastClubIdRoute
  CastControlClubIdRoute: typeof CastControlClubIdRoute
  HRaceRaceIdRoute: typeof HRaceRaceIdRoute
  PRaceRaceIdRoute: typeof PRaceRaceIdRoute
  PricingPageRoute: typeof PricingPageRoute
  AutoLoginUUIDRoute: typeof AutoLoginUUIDRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DemoIndexRoute: typeof DemoIndexRoute
  LogoutIndexRoute: typeof LogoutIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  SignOnIndexRoute: typeof SignOnIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AuthsorterIndexRoute: typeof AuthsorterIndexRoute
  ClubIndexRoute: typeof ClubIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DemoRaceRaceIdRoute: typeof DemoRaceRaceIdRoute
  SignOnRaceRaceIdRoute: typeof SignOnRaceRaceIdRoute
  SignOnSeriesSeriesIdRoute: typeof SignOnSeriesSeriesIdRoute
  AdminClubsClubIdRoute: typeof AdminClubsClubIdRoute
  AdminSettingsDemoRoute: typeof AdminSettingsDemoRoute
  DashboardPrintPaperResultsRaceIdRoute: typeof DashboardPrintPaperResultsRaceIdRoute
  DashboardRaceRaceIdRoute: typeof DashboardRaceRaceIdRoute
  DashboardSeriesSeriesIdRoute: typeof DashboardSeriesSeriesIdRoute
  DashboardMeClubsRoute: typeof DashboardMeClubsRoute
  DashboardMeRacesRoute: typeof DashboardMeRacesRoute
  SignOnGuideIndexRoute: typeof SignOnGuideIndexRoute
  AdminClubsIndexRoute: typeof AdminClubsIndexRoute
  ClubClubNameIndexRoute: typeof ClubClubNameIndexRoute
  DashboardBoatsIndexRoute: typeof DashboardBoatsIndexRoute
  DashboardClubIndexRoute: typeof DashboardClubIndexRoute
  DashboardDocumentationIndexRoute: typeof DashboardDocumentationIndexRoute
  DashboardHardwareIndexRoute: typeof DashboardHardwareIndexRoute
  DashboardRaceIndexRoute: typeof DashboardRaceIndexRoute
  DashboardSeriesIndexRoute: typeof DashboardSeriesIndexRoute
  DashboardSubscriptionIndexRoute: typeof DashboardSubscriptionIndexRoute
  DashboardTrackableIndexRoute: typeof DashboardTrackableIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardMeIndexRoute: typeof DashboardMeIndexRoute
  ClubClubNameRaceRaceIdRoute: typeof ClubClubNameRaceRaceIdRoute
  ClubClubNameSeriesSeriesIdRoute: typeof ClubClubNameSeriesSeriesIdRoute
  ClubClubNameLiveResultsIndexRoute: typeof ClubClubNameLiveResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authsorter/': {
      id: '/authsorter/'
      path: '/authsorter'
      fullPath: '/authsorter'
      preLoaderRoute: typeof AuthsorterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SignOn/': {
      id: '/SignOn/'
      path: '/SignOn'
      fullPath: '/SignOn'
      preLoaderRoute: typeof SignOnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Register/': {
      id: '/Register/'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Logout/': {
      id: '/Logout/'
      path: '/Logout'
      fullPath: '/Logout'
      preLoaderRoute: typeof LogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Demo/': {
      id: '/Demo/'
      path: '/Demo'
      fullPath: '/Demo'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/dashboard/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoLogin/$UUID': {
      id: '/autoLogin/$UUID'
      path: '/autoLogin/$UUID'
      fullPath: '/autoLogin/$UUID'
      preLoaderRoute: typeof AutoLoginUUIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pricing/page': {
      id: '/Pricing/page'
      path: '/Pricing/page'
      fullPath: '/Pricing/page'
      preLoaderRoute: typeof PricingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PRace/$raceId': {
      id: '/PRace/$raceId'
      path: '/PRace/$raceId'
      fullPath: '/PRace/$raceId'
      preLoaderRoute: typeof PRaceRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/HRace/$raceId': {
      id: '/HRace/$raceId'
      path: '/HRace/$raceId'
      fullPath: '/HRace/$raceId'
      preLoaderRoute: typeof HRaceRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CastControl/$clubId': {
      id: '/CastControl/$clubId'
      path: '/CastControl/$clubId'
      fullPath: '/CastControl/$clubId'
      preLoaderRoute: typeof CastControlClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cast/$clubId': {
      id: '/Cast/$clubId'
      path: '/Cast/$clubId'
      fullPath: '/Cast/$clubId'
      preLoaderRoute: typeof CastClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/me/': {
      id: '/dashboard/me/'
      path: '/dashboard/me'
      fullPath: '/dashboard/me'
      preLoaderRoute: typeof DashboardMeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Users/': {
      id: '/dashboard/Users/'
      path: '/dashboard/Users'
      fullPath: '/dashboard/Users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Trackable/': {
      id: '/dashboard/Trackable/'
      path: '/dashboard/Trackable'
      fullPath: '/dashboard/Trackable'
      preLoaderRoute: typeof DashboardTrackableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Subscription/': {
      id: '/dashboard/Subscription/'
      path: '/dashboard/Subscription'
      fullPath: '/dashboard/Subscription'
      preLoaderRoute: typeof DashboardSubscriptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Series/': {
      id: '/dashboard/Series/'
      path: '/dashboard/Series'
      fullPath: '/dashboard/Series'
      preLoaderRoute: typeof DashboardSeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Race/': {
      id: '/dashboard/Race/'
      path: '/dashboard/Race'
      fullPath: '/dashboard/Race'
      preLoaderRoute: typeof DashboardRaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Hardware/': {
      id: '/dashboard/Hardware/'
      path: '/dashboard/Hardware'
      fullPath: '/dashboard/Hardware'
      preLoaderRoute: typeof DashboardHardwareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Documentation/': {
      id: '/dashboard/Documentation/'
      path: '/dashboard/Documentation'
      fullPath: '/dashboard/Documentation'
      preLoaderRoute: typeof DashboardDocumentationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Club/': {
      id: '/dashboard/Club/'
      path: '/dashboard/Club'
      fullPath: '/dashboard/Club'
      preLoaderRoute: typeof DashboardClubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Boats/': {
      id: '/dashboard/Boats/'
      path: '/dashboard/Boats'
      fullPath: '/dashboard/Boats'
      preLoaderRoute: typeof DashboardBoatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$clubName/': {
      id: '/club/$clubName/'
      path: '/club/$clubName'
      fullPath: '/club/$clubName'
      preLoaderRoute: typeof ClubClubNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clubs/': {
      id: '/admin/clubs/'
      path: '/admin/clubs'
      fullPath: '/admin/clubs'
      preLoaderRoute: typeof AdminClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SignOn/Guide/': {
      id: '/SignOn/Guide/'
      path: '/SignOn/Guide'
      fullPath: '/SignOn/Guide'
      preLoaderRoute: typeof SignOnGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/me/races': {
      id: '/dashboard/me/races'
      path: '/dashboard/me/races'
      fullPath: '/dashboard/me/races'
      preLoaderRoute: typeof DashboardMeRacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/me/clubs': {
      id: '/dashboard/me/clubs'
      path: '/dashboard/me/clubs'
      fullPath: '/dashboard/me/clubs'
      preLoaderRoute: typeof DashboardMeClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Series/$seriesId': {
      id: '/dashboard/Series/$seriesId'
      path: '/dashboard/Series/$seriesId'
      fullPath: '/dashboard/Series/$seriesId'
      preLoaderRoute: typeof DashboardSeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Race/$raceId': {
      id: '/dashboard/Race/$raceId'
      path: '/dashboard/Race/$raceId'
      fullPath: '/dashboard/Race/$raceId'
      preLoaderRoute: typeof DashboardRaceRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/PrintPaperResults/$raceId': {
      id: '/dashboard/PrintPaperResults/$raceId'
      path: '/dashboard/PrintPaperResults/$raceId'
      fullPath: '/dashboard/PrintPaperResults/$raceId'
      preLoaderRoute: typeof DashboardPrintPaperResultsRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/demo': {
      id: '/admin/settings/demo'
      path: '/admin/settings/demo'
      fullPath: '/admin/settings/demo'
      preLoaderRoute: typeof AdminSettingsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clubs/$clubId': {
      id: '/admin/clubs/$clubId'
      path: '/admin/clubs/$clubId'
      fullPath: '/admin/clubs/$clubId'
      preLoaderRoute: typeof AdminClubsClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SignOn/Series/$seriesId': {
      id: '/SignOn/Series/$seriesId'
      path: '/SignOn/Series/$seriesId'
      fullPath: '/SignOn/Series/$seriesId'
      preLoaderRoute: typeof SignOnSeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SignOn/Race/$raceId': {
      id: '/SignOn/Race/$raceId'
      path: '/SignOn/Race/$raceId'
      fullPath: '/SignOn/Race/$raceId'
      preLoaderRoute: typeof SignOnRaceRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Demo/Race/$raceId': {
      id: '/Demo/Race/$raceId'
      path: '/Demo/Race/$raceId'
      fullPath: '/Demo/Race/$raceId'
      preLoaderRoute: typeof DemoRaceRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$clubName/LiveResults/': {
      id: '/club/$clubName/LiveResults/'
      path: '/club/$clubName/LiveResults'
      fullPath: '/club/$clubName/LiveResults'
      preLoaderRoute: typeof ClubClubNameLiveResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$clubName/Series/$seriesId': {
      id: '/club/$clubName/Series/$seriesId'
      path: '/club/$clubName/Series/$seriesId'
      fullPath: '/club/$clubName/Series/$seriesId'
      preLoaderRoute: typeof ClubClubNameSeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$clubName/Race/$raceId': {
      id: '/club/$clubName/Race/$raceId'
      path: '/club/$clubName/Race/$raceId'
      fullPath: '/club/$clubName/Race/$raceId'
      preLoaderRoute: typeof ClubClubNameRaceRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CastClubIdRoute: CastClubIdRoute,
  CastControlClubIdRoute: CastControlClubIdRoute,
  HRaceRaceIdRoute: HRaceRaceIdRoute,
  PRaceRaceIdRoute: PRaceRaceIdRoute,
  PricingPageRoute: PricingPageRoute,
  AutoLoginUUIDRoute: AutoLoginUUIDRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DemoIndexRoute: DemoIndexRoute,
  LogoutIndexRoute: LogoutIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  SignOnIndexRoute: SignOnIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AuthsorterIndexRoute: AuthsorterIndexRoute,
  ClubIndexRoute: ClubIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DemoRaceRaceIdRoute: DemoRaceRaceIdRoute,
  SignOnRaceRaceIdRoute: SignOnRaceRaceIdRoute,
  SignOnSeriesSeriesIdRoute: SignOnSeriesSeriesIdRoute,
  AdminClubsClubIdRoute: AdminClubsClubIdRoute,
  AdminSettingsDemoRoute: AdminSettingsDemoRoute,
  DashboardPrintPaperResultsRaceIdRoute: DashboardPrintPaperResultsRaceIdRoute,
  DashboardRaceRaceIdRoute: DashboardRaceRaceIdRoute,
  DashboardSeriesSeriesIdRoute: DashboardSeriesSeriesIdRoute,
  DashboardMeClubsRoute: DashboardMeClubsRoute,
  DashboardMeRacesRoute: DashboardMeRacesRoute,
  SignOnGuideIndexRoute: SignOnGuideIndexRoute,
  AdminClubsIndexRoute: AdminClubsIndexRoute,
  ClubClubNameIndexRoute: ClubClubNameIndexRoute,
  DashboardBoatsIndexRoute: DashboardBoatsIndexRoute,
  DashboardClubIndexRoute: DashboardClubIndexRoute,
  DashboardDocumentationIndexRoute: DashboardDocumentationIndexRoute,
  DashboardHardwareIndexRoute: DashboardHardwareIndexRoute,
  DashboardRaceIndexRoute: DashboardRaceIndexRoute,
  DashboardSeriesIndexRoute: DashboardSeriesIndexRoute,
  DashboardSubscriptionIndexRoute: DashboardSubscriptionIndexRoute,
  DashboardTrackableIndexRoute: DashboardTrackableIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardMeIndexRoute: DashboardMeIndexRoute,
  ClubClubNameRaceRaceIdRoute: ClubClubNameRaceRaceIdRoute,
  ClubClubNameSeriesSeriesIdRoute: ClubClubNameSeriesSeriesIdRoute,
  ClubClubNameLiveResultsIndexRoute: ClubClubNameLiveResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
